3 x (2 5 0 6 8 10 6 7 5 7) x 2 x (8 6 7 9 6 6 2 3 2 3) = (6 15 0 18 24 30 18 21 15 21) x (16 12 14 18 12 12 4 6 4 6) = 1644 <br>

6 x (9 6 7 7 0 1 6 8 1 2) x 5 x (0 2 2 6 7 8 8 3 1 8) = (54 36 42 42 0 6 36 48 6 12) x (0 10 10 30 35 40 40 15 5 40) = 4950
<br>
(2 5 0 6 8 10 6 7 5 7) x (8 6 7 9 6 6 2 3 2 3) = 272
<br>
(9 6 7 7 0 1 6 8 1 2) x (0 2 2 6 7 8 8 3 1 8) = 165



Задание 2

In [18]:
def transpose(matr):
    res=[]
    n=len(matr)
    m=len(matr[0])
    for j in range(m):
        tmp=[]
        for i in range(n):
            tmp=tmp+[matr[i][j]]
        res=res+[tmp]
    return res

matrix = [[2,1,7,4], [5, 6,7,3],[9,8,2,12],[11,14,15,15]]
matrix


[[2, 1, 7, 4], [5, 6, 7, 3], [9, 8, 2, 12], [11, 14, 15, 15]]

In [19]:
for row in matrix:
    for elem in row:
        print(elem, end=' ')
    print()

2 1 7 4 
5 6 7 3 
9 8 2 12 
11 14 15 15 


In [21]:
matrix = transpose(matrix)
for row in matrix:
    for elem in row:
        print(elem, end=' ')
    print()

2 1 7 4 
5 6 7 3 
9 8 2 12 
11 14 15 15 


пункт 5

In [23]:
matrix = [[3,7,8,3,6],[2,5,9,4,13]]
matrix

[[3, 7, 8, 3, 6], [2, 5, 9, 4, 13]]

In [25]:
for row in matrix:
    for elem in row:
        print(elem, end=' ')
    print()

3 7 8 3 6 
2 5 9 4 13 


In [27]:
matrix = transpose(matrix)
for row in matrix:
    for elem in row:
        print(elem, end=' ')
    print()

3 7 8 3 6 
2 5 9 4 13 


Задание 3

In [1]:
from sympy import *
a1, a2 = symbols('a1,a2')

MSE = 1/4 *((1 * a1 +2 * a2 -5)**2 + \
           (5 * a1 + 3 * a2 -6)**2 + \
           (2 * a1 + 4 * a2 -10)**2 + \
           (3 * a1 + 7 * a2 -8)**2)
MSE

0.25*(a1 + 2*a2 - 5)**2 + 0.25*(2*a1 + 4*a2 - 10)**2 + 0.25*(3*a1 + 7*a2 - 8)**2 + 0.25*(5*a1 + 3*a2 - 6)**2

In [32]:
MSE.subs({a1: 0.57, a2: 0.91})

8.56082500000000

In [34]:
MSEa1 = diff(MSE,a1)
MSEa1

19.5*a1 + 23.0*a2 - 39.5

In [36]:
MSEa2 = diff(MSE,a2)
MSEa2

23.0*a1 + 39.0*a2 - 62.0

In [37]:
step = 0.01

In [62]:
import numpy
point = nexpoint
point

array([0.681826382468750, 1.15923265951250], dtype=object)

In [63]:
grad = numpy.array([MSEa1.subs({a1:point[0],a2:point[1]}),
                   MSEa2.subs({a1:point[0],a2:point[1]})])
grad

array([0.457965626928125, -1.10791948223125], dtype=object)

In [64]:
nexpoint = point - grad * step
nexpoint

array([0.677246726199469, 1.17031185433481], dtype=object)

In [65]:
MSE.subs({a1:nexpoint[0],a2:nexpoint[1]})

6.34873371109374